name = "SawyerEliassenSolver"
uuid = "4160a140-ed77-4dbe-8316-dcd1d4ea2f4e"
authors = ["Jamie Hilditch <hilditch@stanford.edu>"]
version = "1.0.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Aqua = "0.8"
DocStringExtensions = "0.8, 0.9"
FFTW = "1"
HDF5 = "0.17.2"
JET = "0.7"
JuliaFormatter = "1.0.56"
LinearAlgebra = "<0.0.1, 1"
Printf = "<0.0.1, 1"
Reexport = "1.2.2"
Statistics = "1.11.1"
Test = "<0.0.1, 1"
julia = "1.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test", "JuliaFormatter"]
